# Generated by Django 3.2.7 on 2021-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_shareablepost_likedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablepost',
            name='media_id',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
