# Generated by Django 3.2.7 on 2021-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_shareablepost_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablepost',
            name='media_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
